import csv
from datetime import datetime

def read_fruits_csv(csv_path):
	items = []
	with open(csv_path, newline='', encoding='utf-8') as csvfile:
		reader = csv.DictReader(csvfile, skipinitialspace=True)
		for row in reader:
			item = row['Item'].strip()
			qty = int(row['Qty'])
			price = float(row['Price'])
			total = qty * price
			items.append({
				'item': item,
				'qty': qty,
				'price': price,
				'total': total
			})
	return items

def generate_report(items, author='System Log'):
	date_str = datetime.now().strftime('%Y-%m-%d')
	report_lines = []
	report_lines.append('='*17 + ' Sales Report ' + '='*17)
	report_lines.append(f'Date        : {date_str}')
	report_lines.append(f'Generated By: {author}')
	report_lines.append('')
	report_lines.append('-'*48)
	report_lines.append(f'{{:<15}}{{:>6}}{{:>11}}{{:>11}}'.format('Item', 'Qty', 'Price($)', 'Total($)'))
	report_lines.append('-'*48)

	subtotal = 0.0
	for item in items:
		report_lines.append(
			f"{item['item']:<15}{item['qty']:>6}{item['price']:>8.2f}{item['total']:>11.2f}"
		)
		subtotal += item['total']

	report_lines.append('-'*48)
	report_lines.append(f'Subtotal:{{:>31.2f}}'.format(subtotal))
	tax = subtotal * 0.05
	report_lines.append(f'Tax (5%):{{:>31.2f}}'.format(tax))
	report_lines.append('-'*48)
	grand_total = subtotal + tax
	report_lines.append(f'Grand Total:{{:>28.2f}}'.format(grand_total))
	report_lines.append('='*48)
	report_lines.append('')
	report_lines.append('* Note: All amounts are in USD.')
	report_lines.append('* Report generated for debug/log purposes only.')
	return '\n'.join(report_lines)

if __name__ == '__main__':
	csv_path = 'new-fruits.csv'
	items = read_fruits_csv(csv_path)
	report = generate_report(items)
	print(report)
