import csv
from datetime import datetime

def generate_sales_report(csv_path):
    items = []
    subtotal = 0.0
    with open(csv_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            item = row['Item']
            qty = int(row['Qty'])
            price = float(row['Price'])
            total = qty * price
            items.append({
                'item': item,
                'qty': qty,
                'price': price,
                'total': total
            })
            subtotal += total
    tax = round(subtotal * 0.05, 2)
    grand_total = round(subtotal + tax, 2)
    return {
        'items': items,
        'subtotal': round(subtotal, 2),
        'tax': tax,
        'grand_total': grand_total
    }

def print_report(report):
    today = datetime.now().strftime('%Y-%m-%d')
    print('================= Sales Report =================')
    print(f'Date        : {today}')
    print('Generated By: System Log')
    print('\n------------------------------------------------')
    print('Item            Qty     Price($)    Total($)')
    print('------------------------------------------------')
    for entry in report['items']:
        print(f"{entry['item']:<14}{entry['qty']:>5}   {entry['price']:>7.2f}   {entry['total']:>9.2f}")
    print('------------------------------------------------')
    print(f"Subtotal: {report['subtotal']:>31.2f}")
    print(f"Tax (5%): {report['tax']:>31.2f}")
    print('------------------------------------------------')
    print(f"Grand Total: {report['grand_total']:>28.2f}")
    print('================================================')
    print('\n* Note: All amounts are in USD.')
    print('* Report generated for debug/log purposes only.')

if __name__ == "__main__":
    csv_path = '001-sales-report/new-fruits.csv'
    report = generate_sales_report(csv_path)
    print_report(report)
